#!/usr/bin/env python3
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""Generate and validate build identity inputs for Good Bear."""

from __future__ import annotations

import argparse
import ast
import json
from pathlib import Path
import sys


class IdentityError(RuntimeError):
    pass


def require(condition: bool, message: str) -> None:
    if not condition:
        raise IdentityError(message)


def load_json(path: Path, label: str) -> dict:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise IdentityError(f"cannot load {label} {path}: {exc}") from exc
    require(isinstance(value, dict), f"{label} must be a JSON object")
    return value


USER_AGENT_PATCH = "0045-good-bear-firefox-user-agent-compatibility.patch"


def verify_user_agent_source(source: Path) -> None:
    """Check the native source owner rather than trusting the identity label."""
    configure_path = source / "browser/moz.configure"
    try:
        configure = ast.parse(configure_path.read_text(encoding="utf-8"))
    except (OSError, SyntaxError) as exc:
        raise IdentityError(f"cannot parse native UA owner {configure_path}: {exc}") from exc
    calls = [node for node in ast.walk(configure)
             if isinstance(node, ast.Call) and isinstance(node.func, ast.Name)
             and node.func.id == "imply_option" and node.args
             and isinstance(node.args[0], ast.Constant)
             and node.args[0].value == "MOZ_APP_UA_NAME"]
    top_level = [node.value for node in configure.body if isinstance(node, ast.Expr)]
    require(len(calls) == 1 and calls[0] in top_level and len(calls[0].args) == 2
            and not calls[0].keywords and isinstance(calls[0].args[1], ast.Constant)
            and calls[0].args[1].value == "Firefox",
            "native MOZ_APP_UA_NAME must unconditionally preserve Firefox")
    toolkit_includes = [node for node in top_level
                        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name)
                        and node.func.id == "include" and node.args
                        and isinstance(node.args[0], ast.Constant)
                        and node.args[0].value == "../toolkit/moz.configure"]
    require(len(toolkit_includes) == 1 and calls[0].lineno < toolkit_includes[0].lineno,
            "native UA identity must precede the toolkit project option")
    toolkit = (source / "toolkit/moz.configure").read_text(encoding="utf-8")
    require('set_define("MOZ_APP_UA_VERSION", depends(milestone.app_version)' in toolkit,
            "native UA version must preserve the upstream milestone owner")
    handler = (source / "netwerk/protocol/http/nsHttpHandler.cpp").read_text(encoding="utf-8")
    for fragment in ('mAppName.AssignLiteral(MOZ_APP_UA_NAME);',
                     'bool isFirefox = mAppName.EqualsLiteral("Firefox");',
                     'mCompatFirefox.AssignLiteral("Firefox/" MOZILLA_UAVERSION);',
                     'if (isFirefox || mCompatFirefoxEnabled)', 'if (!isFirefox)'):
        require(fragment in handler, "upstream HTTP UA construction owner changed")


def render_mozconfig(identity: dict) -> str:
    release = identity["release"]
    build = identity["build"]
    return "\n".join([
        "# Generated by tools/product_identity.py from config/product-identity.json.",
        "# Good Bear 1.0 has one release locale: ru.",
        "ac_add_options --enable-application=browser",
        f"ac_add_options --with-branding={build['branding_directory']}",
        f"ac_add_options --with-app-basename=\"{identity['product']['name']}\"",
        f"ac_add_options --enable-update-channel={release['channel']}",
        "ac_add_options --disable-updater",
        "ac_add_options --disable-crashreporter",
        f"mk_add_options MOZ_CO_LOCALES={release['locale']}",
        f"export MOZ_APP_REMOTINGNAME={release['executable_name']}",
        f"export MOZ_PKG_APPNAME={release['executable_name']}",
        f"export MOZ_PKG_VERSION={build['package_version']}",
        f"export MAR_CHANNEL_ID={build['mar_channel_id']}",
        "export ACCEPTED_MAR_CHANNEL_IDS=" + ",".join(build["accepted_mar_channel_ids"]),
        "",
    ])


def verify_contract(root: Path, identity: dict, release: bool = False) -> None:
    baseline = load_json(root / "config/firefox-baseline.json", "baseline config")
    product = identity.get("product", {})
    version_pair = identity.get("version_pair", {})
    release_identity = identity.get("release", {})
    build = identity.get("build", {})
    compatibility = identity.get("upstream_compatibility", {})
    services = identity.get("services", {})

    require(identity.get("schema_version") == 1, "unsupported product identity schema")
    require(product.get("name") == "Good Bear", "public product name must be Good Bear")
    require(product.get("version") == "1.0" and product.get("display_version") == "1.0",
            "Good Bear product/display version must be 1.0")
    require(version_pair.get("schema_version") == 1,
            "unsupported Good Bear/Firefox version-pair schema")
    require(version_pair.get("ordering") == "good_bear_then_firefox_base",
            "version pair must explicitly order Good Bear before Firefox base")
    require(version_pair.get("good_bear_version") == product.get("version"),
            "version pair does not match the Good Bear product version")
    require(release_identity.get("platform") == "ubuntu", "Good Bear 1.0 only releases for Ubuntu")
    require(release_identity.get("architecture") == "amd64", "Good Bear 1.0 architecture must be amd64")
    require(release_identity.get("locale") == "ru", "release locale must be ru")
    require(release_identity.get("shipped_locales") == ["ru"],
            "ru must be the only shipped locale")
    require(release_identity.get("internal_source_locale") == "en-US",
            "the upstream source locale must remain explicit")
    require(release_identity.get("internal_source_locale_disposition") ==
            "build_fallback_only_not_shipped_separately",
            "en-US may only be an internal source/fallback locale")

    forbidden_public_values = {"firefox", "mozilla", "mozilla firefox"}
    for key in ("package_name", "executable_name", "desktop_file_id", "desktop_display_name"):
        value = release_identity.get(key)
        require(isinstance(value, str) and value, f"release.{key} is missing")
        require(value.lower() not in forbidden_public_values,
                f"release.{key} must not present the product as Firefox or Mozilla")
    require(release_identity.get("profile_namespace") == "goodbear",
            "profile namespace must isolate Good Bear from Firefox")
    require(release_identity.get("channel") == "goodbear", "release channel must be goodbear")

    firefox_version = baseline.get("version")
    require(version_pair.get("firefox_base_version") == firefox_version,
            "version pair does not match the pinned Firefox baseline")
    expected_about = f"Good Bear {product['display_version']} (Firefox {firefox_version})"
    require(version_pair.get("canonical_about_ru") == expected_about,
            "Russian About version pair is not canonical")
    require(version_pair.get("package_version") == build.get("package_version") ==
            f"{product['version']}+firefox{firefox_version}",
            "package version does not carry the declared version pair")
    require(compatibility.get("firefox_version") == firefox_version,
            "identity contract does not match the pinned Firefox baseline")
    app_version = compatibility.get("application_version", {})
    require(app_version.get("value") == firefox_version and app_version.get("disposition") == "preserve",
            "MOZ_APP_VERSION must preserve the pinned Firefox compatibility version")
    app_id = compatibility.get("application_id", {})
    require(app_id.get("value") == "{ec8030f7-c20a-464f-9b0e-13a3a9e97384}" and
            app_id.get("disposition") == "preserve" and app_id.get("reason"),
            "Firefox application ID needs an explicit preserved disposition")
    ua_product = compatibility.get("user_agent_product", {})
    require(ua_product.get("value") == "Firefox" and ua_product.get("disposition") == "preserve" and
            ua_product.get("reason"), "Firefox UA token needs an explicit compatibility disposition")

    owners = identity.get("upstream_owner_evidence", [])
    required_owners = {
        "browser/moz.configure", "build/moz.configure/init.configure", "toolkit/moz.configure",
        "build/moz.configure/update-programs.configure", "toolkit/xre/nsXREDirProvider.cpp",
    }
    revision = baseline.get("vcs", {}).get("revision")
    require(isinstance(owners, list) and len(owners) == len(required_owners) and
            all(isinstance(owner, dict) for owner in owners) and
            {owner.get("path") for owner in owners} == required_owners and
            isinstance(revision, str) and len(revision) == 40 and
            all(owner.get("revision") == revision and owner.get("decision") for owner in owners),
            "product identity owners must match the pinned Firefox source revision")

    for service_name in ("application_updater", "crash_reporter"):
        service = services.get(service_name, {})
        require(service.get("enabled") is False, f"{service_name} must be disabled for Good Bear 1.0")
        require(service.get("endpoints") == [], f"{service_name} must not inherit an endpoint")

    require(build.get("mar_channel_id") == "goodbear-release",
            "MAR channel must be independent from Mozilla channels")
    require(build.get("accepted_mar_channel_ids") == ["goodbear-release"],
            "only the Good Bear MAR channel may be accepted")

    expected_mozconfig = render_mozconfig(identity)
    mozconfig_path = root / "overlay" / build["mozconfig_path"]
    require(mozconfig_path.read_text(encoding="utf-8") == expected_mozconfig,
            f"generated mozconfig is stale: {mozconfig_path}")

    series = (root / "patches/series").read_text(encoding="utf-8").splitlines()
    entries = [line.strip() for line in series if line.strip() and not line.lstrip().startswith("#")]
    require("0001-good-bear-product-identity.patch" in entries,
            "product identity patch is not listed in patches/series")
    require(USER_AGENT_PATCH in entries,
            "native Firefox UA compatibility patch is not listed in patches/series")
    ua_patch = (root / "patches" / USER_AGENT_PATCH).read_text(encoding="utf-8")
    require('+imply_option("MOZ_APP_UA_NAME", "Firefox")' in ua_patch,
            "native Firefox UA compatibility patch omits MOZ_APP_UA_NAME")
    identity_patch = (root / "patches/0001-good-bear-product-identity.patch").read_text(
        encoding="utf-8"
    )
    for fragment in (
        "+MOZ_APP_NAME=goodbear",
        "+MOZ_BRANDING_DIRECTORY=browser/branding/goodbear",
        "+1.0",
        '+imply_option("MOZ_APP_VENDOR", "Good Bear Project")',
        '+imply_option("MOZ_APP_PROFILE", "goodbear")',
        ' imply_option("MOZ_APP_ID", "{ec8030f7-c20a-464f-9b0e-13a3a9e97384}")',
        '+pref("breakpad.reportURL", "");',
        '+pref("browser.tabs.crashReporting.sendReport", false);',
    ):
        require(fragment in identity_patch, f"product identity patch is missing: {fragment}")

    branding = root / "overlay" / build["branding_directory"]
    for relative in ("moz.build", "locales/moz.build", "locales/jar.mn", "configure.sh",
                     "locales/en-US/brand.ftl", "locales/en-US/brand.properties",
                     "pref/firefox-branding.js", "default16.png", "default32.png",
                     "default48.png", "default64.png", "default128.png"):
        require((branding / relative).is_file(), f"branding identity input is missing: {relative}")
    configure_text = (branding / "configure.sh").read_text(encoding="utf-8")
    ftl_text = (branding / "locales/en-US/brand.ftl").read_text(encoding="utf-8")
    properties_text = (branding / "locales/en-US/brand.properties").read_text(encoding="utf-8")
    require('MOZ_APP_DISPLAYNAME="Good Bear"' in configure_text,
            "configured application display name must be Good Bear")
    for key in ("-brand-shorter-name", "-brand-short-name", "-brand-shortcut-name",
                "-brand-full-name", "-brand-product-name"):
        require(f"{key} = Good Bear" in ftl_text,
                f"branding variable {key} must expose Good Bear")
    for key in ("brandShorterName", "brandShortName", "brandFullName"):
        require(f"{key}=Good Bear" in properties_text,
                f"branding property {key} must expose Good Bear")

    if release:
        artwork = identity.get("artwork", {})
        require(artwork.get("release_status") == "approved_original_assets",
                "release blocked: approved original Good Bear artwork is not available")
        for relative in artwork.get("required_release_paths", []):
            require((root / "overlay" / relative).is_file(),
                    f"release blocked: required original artwork is missing: {relative}")


def main() -> int:
    from host_build_context import SOURCE

    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", type=Path, default=root / "config/product-identity.json")
    parser.add_argument("--write-mozconfig", action="store_true")
    parser.add_argument("--release", action="store_true",
                        help="also enforce release artwork approval and presence")
    args = parser.parse_args()
    try:
        identity = load_json(args.config, "product identity")
        if args.write_mozconfig:
            destination = root / "overlay" / identity["build"]["mozconfig_path"]
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(render_mozconfig(identity), encoding="utf-8")
            print(f"Wrote {destination}", flush=True)
        verify_contract(root, identity, release=args.release)
        verify_user_agent_source(SOURCE)
    except (IdentityError, KeyError, OSError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    print("Good Bear product identity verified", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
